### PR TITLE
Change GPL v2 to LGPL v2.1 or later, convert README to markdown

### PR DESCRIPTION
**Pull request by vasily-v-ryabov**

### CODE REVIEW

**Comment by frafra** [comment]
Looks fine to me :thumbsup:

**Comment by frafra** [comment]
59 files have a copyright notice and most of them contain a GPL header.
Have we obtained the permission for this change from every author?

```
$ (shopt -s globstar; for f in **; do [ -f "$f" ] && sed -n 's:.*Copyright\( (C)\)[0-9, ]*[-]*[0-9 ]*\(.*\):\2:p' "$f"; done) | grep -v '{year}' | sort -u
Alex Badea <vamposdecampos@gmail.com>
Arun Balasubramanian <med.diagnostix@gmail.com>
David Bronke <whitelynx@gmail.com>
David H. Bronke <whitelynx@gmail.com>
Free Software Foundation, Inc.
Jeffrey Boser <verin@lvcm.com>
Mike Meyer <mwm@mired.org>
Outpost Embedded, LLC
Peter Liljenberg
Peter Liljenberg <peter.liljenberg@gmail.com>
Peter Liljenberg <petli@ctrl-c.liu.se>
```

**Comment by vasily-v-ryabov** [comment]
Thank you for pointing it out! I see the following people wrote few examples (all the copyrights are in `examples` folder):
```
Alex Badea <vamposdecampos@gmail.com>
Arun Balasubramanian <med.diagnostix@gmail.com>
Jeffrey Boser <verin@lvcm.com>

Outpost Embedded, LLC == Forest Bond <forest.bond@rapidrollout.com> # probably his work activity
```

I can contact them all about the LGPL choice including Forest who may ask his legal department for permission. In case there were no answers we may consider removing/rewriting affected examples.

**Comment by vasily-v-ryabov** [comment]
It looks like Jeffrey's email doesn't exist any more. I cannot find him on the GitHub. He is an author of extension `Xlib\ext\shape.py`.
We may think about excluding or rewriting this extension if we couldn't contact Jeffrey.

**Pull request merged**
