### PR TITLE
Py2/Py3 compatibility fixes (relative imports, new->types etc.)

### PR DESCRIPTION
**Pull request by vasily-v-ryabov**
I've started massive fixes for Py2/Py3 compatibility. Many imports are made relative. Deprecated module `new` is replaced with the `types` one. There is only one conditional change:

* `types.ClassType` works in Py2
* `types.new_class` works in Py3.3+

Travis CI runs Py3.3/3.4/3.5 tests as well. Py2.6/2.7 are 100% OK, Py3 tests are failing for now. Next steps are to replace many things like `string.split()` functions with method `split()` of the string object.

### CODE REVIEW

**Comment by frafra** [comment]
Hey @vasily-v-ryabov, great work! It looks fine to me.

What do you think about moving compatibility code for Py2 on top instead of using if clauses inside the code? Something like this:
```
if not hasattr(types, 'new_class'):
    types.new_class = types.ClassType
```

**Comment by vasily-v-ryabov** [comment]
I think assigning attributes to a built-in module can potentially take an unpredictable side effect (a python-xlib user can rely on the same attribute while using `types` in his own code not connected with python-xlib).

**Comment by frafra** [comment]
You're right, it wouldn't be a good solution, even if I'm not a fan of Py2/3 switches inside the main code.

**Comment by vasily-v-ryabov** [comment]
Probably we need to review the whole approach at the architecture level so `types` module might be fully eliminated with more elegant architecture. But I'm not ready to suggest something right now.

**Comment by frafra** [comment]
Me too. I agree with you.

**Pull request merged**
