### PR TITLE
test: replace mock dependency with unittest.mock

### PR DESCRIPTION
**Pull request by Foxboron**

### CODE REVIEW

**Comment by vasily-v-ryabov** [comment]
Since Py2.7 is still supported, this PR should be postponed till we have time to drop Py2.7 support.

**Comment by Foxboron** [comment]
We could wrap this into a `ImportError` exception thing and stick the dependency as a "python2.7 only" thing?

**Comment by Foxboron** [comment]
Revised so we use the mock library on any python installations below version 3.3, which is when `unittest.mock` was introduced.

**Comment by Foxboron** [comment]
Any updates on this?

**Pull request closed without merging**
