### PR TITLE
NV-CONTROL: bugfixes and new features

### PR DESCRIPTION
**Pull request by leinardi**
- Fixed bug where `get_cooler_manual_control_enabled` was returning `False` instead of `None` making not possible differentiate if manual control was actually disabled (`False`) or not possible at all (`None`) due to the Coolbit 4 not being set.
- Fixed bug where `get_gpu_nvclock_offset_range` was always returning the offset of the first power level.
- Added `get_clock_info` method and aligned method names to the respective methods from NVIDIA Management Library.

### CODE REVIEW

**Comment by leinardi** [comment]
@vasily-v-ryabov @benoit-pierre let me know if I should do anything for this PR.

**Comment by leinardi** [comment]
@vasily-v-ryabov @benoit-pierre any news about this PR?

**Comment by tim77** [comment]
@vasily-v-ryabov please release a new version of `python-xlib` with this commit. There is awesome [long waited app for Linux](https://gitlab.com/leinardi/gwe) users but we cant push it in official repos because of [reasons](https://gitlab.com/leinardi/gwe/issues/52). :)

**Comment by vasily-v-ryabov** [comment]
Hi @tim77 @leinardi my apologies for long waiting. 0.26 is now published on PyPI. Hope it still can be useful.

**Comment by tim77** [comment]
Yay. No prob @vasily-v-ryabov review process and testing requires time, we all know that. And yes, this is useful of course. Thank you!

**Pull request merged**
