### PR TITLE
A collection of patches from the Fedora package

### PR DESCRIPTION
**Pull request by opoplawski**
These are all of the patches carried by the Fedora python-xlib package, rebased for current master.

### CODE REVIEW

**Comment by benoit-pierre** [comment]
It would be better if you rewrote the history to fix the offending patch (tabs instead of spaces).

**Comment by benoit-pierre** [comment]
And use the opportunity to fix the comment:
> yet this code fixes a the case

**Comment by opoplawski** [comment]
How's this?

**Comment by benoit-pierre** [comment]
Good. I'm fine with all those changes except for `Do not depend on the existence of ~/.Xauthority`: clearly, we're missing something in the `new_auth` code, and we should fix it, rather than rely on falling back to the `old_auth` code path that introduce a dependency on the presence of the `xauth` program.

**Comment by benoit-pierre** [comment]
I tested with slim 1.3.6 and it works fine, so I'd drop both 0286759383f09e9e7ceddc5534a72797f5ef06c5 and 5f40127601c3bf872441bbd9c2da432cdbe1c315. Frankly, I'm not sure about 79c2f5a67d950a99948921fcc2a28b81856de3cc either, it's really more like a hack than a proper fix: the code is supposed to handle the fact that multiple reads are needed, and there has been a few changes since those ancient patches...

**Comment by benoit-pierre** [comment]
After reviewing this again:
- 79c2f5a **Increase receiving buffer to 4096 bytes:** is still not necessary IMHO
- 97b388a **In "DISPLAY=unix:0.0", "unix" is not a hostname:** has been superseded by #69
- 0286759 **Fall back to unix:0 for `localhost:0`:** is already handled by the code (and should now work fine with Python 3 thanks to #72)
- 1685194 **Fix spelling of rhomboid:** has been cherry-picked in #70
- 5f40127 **Do not depend on the existence of ~/.Xauthority:** has been superseded by #67
- ea4d2fe **Fix perl usage:** has been cherry-picked in #70

So I think we should close this PR.

**Comment by opoplawski** [comment]
Thanks for reviewing.

**Pull request closed without merging**
